version: 2

# This config file uses YAML aliases
# http://blog.daemonl.com/2016/02/yaml.html
# https://github.com/cyklo/Bukkit-OtherBlocks/wiki/Aliases-(advanced-YAML-usage)
aliases:

  # Common configuration for all jobs
  - &defaults
    working_directory: ~/build
    docker:
      - image: circleci/openjdk:8-jdk

  - &release_filter
    filters:
      tags:
        only: /.*/
      branches:
        ignore: /.*/

jobs:

  build_project:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - project-dependencies-{{ checksum "build.gradle" }}
            - project-dependencies
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/
      - run:
          name: Test and build kafka-connectors project
          command: ./gradlew clean build
      - save_cache:
          key: project-dependencies-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/

# Ethereum Images
  deploy_chain_pumps_ethereum_image:
     <<: *defaults
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.11.0-ce
       - run:
           name: Build Ethereum Pump Image
           command: |
             docker build -t build/pump-eth -f ./pumps/ethereum/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/pump-eth cybernode/chain-pump-ethereum:$CIRCLE_TAG
             docker push cybernode/chain-pump-ethereum:$CIRCLE_TAG

  deploy_chain_dumps_ethereum_image:
     <<: *defaults
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.11.0-ce
       - run:
           name: Build Ethereum Dump Image
           command: |
             docker build -t build/dump-eth -f ./dumps/ethereum/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/dump-eth cybernode/chain-dump-ethereum:$CIRCLE_TAG
             docker push cybernode/chain-dump-ethereum:$CIRCLE_TAG

  deploy_chain_address_ethereum_image:
     <<: *defaults
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.11.0-ce
       - run:
           name: Build Ethereum Address Summary Image
           command: |
             docker build -t build/address-summary-eth -f ./address-summary/ethereum/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/address-summary-eth cybernode/chain-address-ethereum:$CIRCLE_TAG
             docker push cybernode/chain-address-ethereum:$CIRCLE_TAG

# Common Images             
  deploy_engine_api_chains_image:
     <<: *defaults
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.11.0-ce
       - run:
           name: Chains Search Api Image
           command: |
             docker build -t build/search-api -f ./search-api/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/address-summary-eth cybernode/engine-api-chains:$CIRCLE_TAG
             docker push cybernode/engine-api-chains:$CIRCLE_TAG

workflows:
  version: 2

  search_build:
    jobs:
      - build_project
      - deploy_chain_pumps_ethereum_image:
          <<: *release_filter
          requires:
            - build_project
      - deploy_chain_dumps_ethereum_image:
          <<: *release_filter
          requires:
            - build_project
      - deploy_chain_address_ethereum_image:
          <<: *release_filter
          requires:
            - build_project
      - deploy_engine_api_chains_image:
          <<: *release_filter
          requires:
            - build_project
