version: '3.3'
services:

  prometheus:
    network_mode: host
    container_name: prometheus
    restart: on-failure
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"

  grafana:
    network_mode: host
    container_name: grafana3
    restart: on-failure
    image: grafana/grafana:5.0.0-beta4
#    ports:
#      - "3000:3000"