

version: '3'
services:

  cs-elassandra:
    image: strapdata/elassandra:2.4.5.5
    volumes:
      - /opt/cyberfund/search/elassandra:/var/lib/cassandra
    ports:
        - "9042:9042"
        - "9200:9200"
        - "9300:9300"
        - "7199:7199"
    environment:
          CASSANDRA_DC: LOCAL_DEVELOPMENT
          CASSANDRA_CLUSTER_NAME: CYBERNODE


  cs-zoo:
    image: confluentinc/cp-zookeeper:3.3.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
    volumes:
      - /opt/cyberfund/search/zoo/data:/var/lib/zookeeper/data
      - /opt/cyberfund/search/zoo/log:/var/lib/zookeeper/log



  cs-kafka:
    image: confluentinc/cp-kafka:3.3.0
    ports:
      - "9092:9092"
      - "1099:1099"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: cs-zoo:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://cs-kafka:9092
      KAFKA_JMX_PORT: 1099
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
    volumes:
      - /opt/cyberfund/search/kafka:/var/lib/kafka



  cs-kafka-manager:
    image: hlebalbau/kafka-manager:1.3.3.14
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "cs-zoo:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null



  cs-kafka-connect:
    image: cybernode/cn-kafka-connectors:release-0.5.3
    ports:
      - "8083:8083"
    environment:

      CONNECT_REST_ADVERTISED_HOST_NAME: "cs-kafka-connect"
      CONNECT_REST_ADVERTISED_PORT: "8083"
      CONNECT_REST_PORT: 8083

      CONNECT_BOOTSTRAP_SERVERS: cs-kafka:9092
      CONNECT_ZOOKEEPER_CONNECT: cs-zoo:2181

      CONNECT_GROUP_ID: "cybernode"
      CONNECT_CONFIG_STORAGE_TOPIC: "cybernode.config"
      CONNECT_OFFSET_STORAGE_TOPIC: "cybernode.offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "cybernode.status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 5000

      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"

      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"

      CONNECT_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      CONNECT_ACCESS_CONTROL_ALLOW_METHODS: 'GET,OPTIONS,HEAD,POST,PUT,DELETE'

  cs-bitcoin-process:
    image: cybernode/cs-bitcoin-processor:release-0.5.3
    environment:
      CASSANDRA_CONNECTION: cs-elassandra
      KAFKA_CONNECTION: cs-kafka:9092

  cs-search-api:
    image: cybernode/cs-search-api:release-0.5.3
    ports:
      - "8085:8085"
    environment:
      ELASTIC_HOST_CONNECTION: cs-elassandra
      ELASTIC_PORT_CONNECTION: 9300
      ELASTIC_CLUSTER_NAME: CYBERNODE

  cs-kafka-connect-ui:
    image: landoop/kafka-connect-ui:0.9.2
    ports:
      - "8000:8000"
    environment:
      CONNECT_URL: cs-kafka-connect:8083

  cs-btcd:
    image: cybernode/bitcoin-btcd
    ports:
      - "8334:8334"
    command: "--rpcuser=cyber --rpcpass=cyber --rpclisten=0.0.0.0:8334 --notls"
    volumes:
      - /cyberdata:/cyberdata
 
