

version: '3.3'
services:

  cs-elassandra:
    image: strapdata/elassandra:2.4.5.5
    volumes:
      - /opt/cyberfund/markets/elassandra:/var/lib/cassandra
    ports:
        - "9042:9042"
        - "9200:9200"
        - "7199:7199"
    environment:
          CASSANDRA_DC: LOCAL_DEVELOPMENT
          CASSANDRA_CLUSTER_NAME: CYBERNODE


  cs-zoo:
    image: confluentinc/cp-zookeeper:3.3.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
    volumes:
      - /opt/cyberfund/markets/zoo/data:/var/lib/zookeeper/data
      - /opt/cyberfund/markets/zoo/log:/var/lib/zookeeper/log



  cs-kafka:
    image: confluentinc/cp-kafka:3.3.0
    ports:
      - "9092:9092"
      - "1099:1099"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://cn-kafka:9092
      KAFKA_JMX_PORT: 1099
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
    volumes:
      - /opt/cyberfund/markets/kafka/data:/var/lib/kafka/data



  cs-kafka_manager:
    image: hlebalbau/kafka-manager:1.3.3.14
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zoo:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null



  cs-kafka-connect:
    image: cybernode/cn-kafka-connectors:release-0.5.2
    ports:
      - "8083:8083"
    environment:

      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_REST_ADVERTISED_PORT: "8083"
      CONNECT_REST_PORT: 8083

      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_ZOOKEEPER_CONNECT: zoo:2181

      CONNECT_GROUP_ID: "cybernode"
      CONNECT_CONFIG_STORAGE_TOPIC: "cybernode.config"
      CONNECT_OFFSET_STORAGE_TOPIC: "cybernode.offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "cybernode.status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 5000

      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"

      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"

      CONNECT_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      CONNECT_ACCESS_CONTROL_ALLOW_METHODS: 'GET,OPTIONS,HEAD,POST,PUT,DELETE'

  cs-kafka-bitcoin:
    image: cybernode/cs-bitcoin-processor:release-0.5.2
    environment:
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_REST_ADVERTISED_PORT: "8083"
      CONNECT_REST_PORT: 8083


  cs-kafka-connect-ui:
    image: landoop/kafka-connect-ui:0.9.2
    ports:
      - "8000:8000"
    environment:
      CONNECT_URL: kafka-connect:8083
