openapi: 3.0.1
servers:
  - url: 'http://staging.cyber.fund:32901'
info:
  description: Empty description
  version: 1.0.0
  title: Cyber.Search Bitcoin API
tags:
  - name: bitcoin
    description: Access to Bitcoin chain entites
paths:

  '/bitcoin/block/{blockNumber}':
    get:
      tags:
        - bitcoin
      summary: Find bitcoin block by number
      description: Returns a block
      operationId: getBlockByNumber
      parameters:
        - name: blockNumber
          in: path
          description: Number of the block
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 'Block found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BitcoinBlock'
        '400':
          description: 'Invalid block number supplied'
        '404':
          description: 'Block not found'


  '/bitcoin/block/{blockNumber}/transactions':
    get:
      tags:
        - bitcoin
      summary: 'Download block transactions'
      description: Returns a block transactions
      operationId: getBlockByNumber
      parameters:
        - name: blockNumber
          in: path
          description: Number of the block
          required: true
          schema:
            type: integer
            format: int64
        - name: count
          in: query
          description: 'How many transactions to load (max value for all transactions)'
          required: false
          schema:
            type: integer
            format: int64
            minimum: 0
            default: 50
        - name: offset
          in: query
          description: 'Tx index offset in block'
          required: false
          schema:
            type: integer
            format: int64
            minimum: 0
            default: 0
      responses:
        '200':
          description: 'Block found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BitcoinBlockTx'
        '400':
          description: "Invalid 'blockNumber', 'count' or 'offset' parameters"
        '404':
          description: 'Block not found'


  '/bitcoin/address/{address}/transactions':
    get:
      tags:
        - bitcoin
      summary: 'Download address transactions'
      description: 'Returns address transactions sorted by time (most recent first)'
      operationId: getAddressResentTransactons
      parameters:
        - name: address
          in: path
          description: 'Given address'
          required: true
          schema:
            type: string
        - name: count
          in: query
          description: 'How many transactions to load (max value for all rest transactions)'
          required: false
          schema:
            type: integer
            format: int64
            minimum: 0
            default: 20
        - name: offset
          in: query
          description: 'Tx offset in address list (sorted by time, most recent first)'
          required: false
          schema:
            type: integer
            format: int64
            minimum: 0
            default: 0
      responses:
        '200':
          description: 'Address transactions found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BitcoinAddressTx'
        '400':
          description: "Invalid 'address', 'count' or 'offset' parameters"
        '404':
          description: 'Address not found'


components:
  schemas:

# Search Previews

    BitcoinBlockPreview:
      type: object
      properties:
        hash:
          type: string
        height:
          type: integer
          format: int64
        time:
          type: string
          format: date-time
        tx_number:
          type: integer
          format: int32
        total_outputs_value:
          type: string

    BitcoinTxPreviewIO:
       type: object
       properties:
         addresses:
          type: array
          items:
            type: string
         amount:
           type: string


    BitcoinTxPreview:
      type: object
      properties:
        txid:
          type: string
        block_hash:
          type: string
        block_number:
          type: integer
          format: int64
        block_time:
          type: string
          format: date-time
        fee:
          type: string
        total_output:
          type: string

# Raw API Entities

    BitcoinBlock:
      allOf:
        - $ref: '#/components/schemas/BitcoinBlockPreview'
        - type: object
          properties:
            hash:
              type: string
            height:
              type: integer
              format: int64
            time:
              type: string
              format: date-time
            nonce:
              type: integer
              format: int64
            merkleroot:
              type: string
            size:
              type: integer
              format: int32
            version:
              type: integer
              format: int32
            weight:
              type: integer
              format: int32
            bits:
              type: string
            difficulty:
              type: number
            tx_number:
              type: integer
              format: int32
            total_outputs_value:
              type: string
            transactionPreviews:
              type: array
              items:
                $ref: "#/components/schemas/BitcoinBlockTx"

    BitcoinBlockTx:
      type: object
      properties:
        hash:
          type: string
        block_number:
          type: integer
          format: int64
        fee:
          type: string
        ins:
          type: array
          items:
            $ref: "#/components/schemas/BitcoinTxPreviewIO"
        outs:
          type: array
          items:
            $ref: "#/components/schemas/BitcoinTxPreviewIO"


    BitcoinTx:
      allOf:
        - $ref: '#/components/schemas/BitcoinTxPreview'
        - type: object
          properties:
            coinbase:
              type: string
            size:
              type: integer
              format: int32
            total_input:
              type: string
            merkleroot:
              type: string

    BitcoinTxIn:
       type: object
       properties:
         addresses:
          type: array
          items:
            type: string
         amount:
           type: string
         asm:
           type: string
         tx_id:
           type: string
         tx_out:
           type: integer
           format: int32

    BitcoinTxOut:
       type: object
       properties:
         addresses:
          type: array
          items:
            type: string
         amount:
           type: string
         asm:
           type: string
         tx_id:
           type: string
         tx_out:
           type: integer
           format: int32


    BitcoinContractTx:
      type: object
      properties:
        hash:
          type: string
        block_number:
          type: integer
          format: int64
        block_time:
          type: string
          format: date-time
        fee:
          type: number
        ins:
          type: array
          items:
            $ref: "#/components/schemas/BitcoinTxPreviewIO"
        outs:
          type: array
          items:
            $ref: "#/components/schemas/BitcoinTxPreviewIO"